// Autogenerated by gomgen
package model

import (
	"database/sql"
	"time"
)

// database connnection
var theDb *sql.DB

// register db object for the models
func Register(db *sql.DB) error {
	theDb = db
	return nil
}

type Article struct {
	Id         int
	Active     bool
	Title      string
	Content    string
	CreateDate time.Time
	UpdateDate time.Time
	CategoryId int
}

// Scan Article from rows object
func (this *Article) Scan(rows *sql.Rows) error {
	var CreateDate, UpdateDate string
	err := rows.Scan(&this.Id, &this.Active, &this.Title, &this.Content, &CreateDate, &UpdateDate, &this.CategoryId)
	if err != nil {
		return err
	}
	this.CreateDate, _ = time.Parse("2006-01-02 15:04:05", CreateDate)
	this.UpdateDate, _ = time.Parse("2006-01-02 15:04:05", UpdateDate)
	return nil
}

type Category struct {
	Id   int
	Name string
}

// Scan Category from rows object
func (this *Category) Scan(rows *sql.Rows) error {
	return rows.Scan(&this.Id, &this.Name)
}
