package gomgen

/**************************************************
 * File header, imports and db part
 **************************************************/
const headerTpl = `// Autogenerated by gomgen

import (
	{{range $k, $v := .Imports}}"{{ $k }}"
	{{end}}
)

// database connnection
var theDb *sql.DB

// register db object for the models
func Register(db *sql.DB) error {
	theDb = db
	return nil
}
`

/**************************************************
 * Generate entity struct type with the fields
 **************************************************/
const entityStructTpl = `
type {{ .EntitySingular }} struct {
	{{range $i, $field := .Fields }}{{ $field.Name }} {{ $field.GoType }}
	{{end}}
}
`

/**************************************************
 * Scan data from the rows object into the entity
 **************************************************/
const scanEntityTpl = `
// Scan {{.EntitySingular}} from rows object
func (this *{{.EntitySingular}}) scan(rows *sql.Rows) error {
	err := rows.Scan()
	if err != nil {
		return err
	}
	return nil
}
`
